module.exports.accountPermissions = require('./accounts')
module.exports.userPermissions = require('./users')
module.exports.rolePermissions = require('./roles')
module.exports.departmentPermissions = require('./departments')
module.exports.incidentPermissions = require('./incidents')
module.exports.taskPermissions = require('./tasks')
module.exports.colorpalettePermissions = require('./colorpalettes')
